name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.2
    - name: Restore Dependencies
      run: dotnet restore ./Code/Synnotech.Migrations.sln
    - name: Build Solution
      run: dotnet build ./Code/Synnotech.Migrations.sln -c Release --no-restore
    - name: Test Synnotech.Migrations.Core
      run: dotnet test ./Code/tests/Synnotech.Migrations.Core.Tests/Synnotech.Migrations.Core.Tests.csproj -c Release --no-build --verbosity normal
    - name: Copy Test Settings for Synnotech.Migrations.RavenDB
      run: cp ./.github/workflows/testsettings.Build.RavenDB.json ./Code/tests/Synnotech.Migrations.RavenDB.Tests/bin/Release/net5.0/testsettings.Build.json
    - name: Test Synnotech.Migrations.RavenDB
      run: dotnet test ./Code/tests/Synnotech.Migrations.RavenDB.Tests/Synnotech.Migrations.RavenDB.Tests.csproj -c Release --no-build --verbosity normal
