name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore ./Code/Synnotech.Migrations.sln
    - name: Build
      run: dotnet build ./Code/Synnotech.Migrations.sln -c Release --no-restore
    - name: Test Synnotech.Migrations.Core
      run: dotnet test ./Code/tests/Synnotech.Migrations.Core.Tests/Synnotech.Migrations.Core.Tests.csproj -c Release --no-build --verbosity normal
